#!/bin/bash

help_text () {
  while IFS= read line; do
    printf "%s\n" "$line"
  done <<EOF
  USAGE: ku [OPTIONS...]

  -h    Show this help text
  -e    Eject device when finished

  ku is a cli tool that easily formats and uploads your comics to kindle

EOF
}

while getopts "he" name;
do
  case "$name" in
    h) help_text
       exit;;
    e) eject=true;;
    ?) ;;
  esac
done
shift "$((OPTIND-1))"

if [[ -z "$eject" ]]; then
  eject=false;
fi

configDir=$HOME/.config/bookUp
configList=$configDir/list
cd $HOME/personal
mkdir $HOME/personal/books
bookDir=$HOME/personal/books
cd $bookDir;

selected=$(find "$HOME/rabbithole/books" -mindepth 1 -maxdepth 1 | fzf)

if [[ -z $selected ]]; then
  exit 0
fi

cp -r "$selected" "$bookDir/"

baseName="$(basename "${selected%.*}")"
if [[ "$selected" == *"rar"* ]]; then
  unrar x "$bookDir/${baseName}.rar"
  rm -rf "$bookDir/${baseName}.rar";
fi

if [[ "$selected" == *"zip"* ]]; then
  unzip "$bookDir/${baseName}.zip"
  rm -rf "$bookDir/${baseName}.zip";
fi

arr=($(echo "${bookDir}/*"))
IFS=$'\n'
noInner=true
for file in "$arr"
do
  directory=($(echo "${file}/*"))
  for f in `find "$file" -name "*.cbz"`
  do
    noInner=false
    ebook-convert "$(echo ${f%.*}).cbz" "$(basename ${f%.*}).mobi" --right2left --output-profile "kindle_pw"
  done

  for f in `find "$file" -name "*.zip"`
  do
    noInner=false
    ebook-convert "$(echo ${f%.*}).cbz" "$(basename ${f%.*}).mobi" --right2left --output-profile "kindle_pw"
  done

  for f in `find "$file" -type d -mindepth 1 -maxdepth 1`
  do
    noInner=false
    zip -r "$(basename ${f}).cbz" "$f"
    ebook-convert "$(basename ${f}).cbz" "$(basename ${f}).mobi" --right2left --output-profile "kindle_pw"
  done

  if [[ $noInner == true ]]; then
    echo $noInner
    base="$(baseName "$file")"
    if [[ "$base" != *"rar"* || "$base" != *"zip"* ]]; then
      zip -r "$file.cbz" "$file"
      ebook-convert "$(echo $file).cbz" "$(echo $file).mobi" --right2left --output-profile "kindle_pw"
    fi
  fi
done

for file in `find "$bookDir" -name "*.mobi"`
do
  ebook-device cp "$(basename $file)" dev:/documents/
done

if [[ "$eject" == true ]]; then
  ebook-device eject
fi

cd $HOME
rm -rf $HOME/personal/books
